apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-4fbt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-4fbt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-4fbt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-4fbt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-4fbt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-frhv-tenant/rhtap-demo-app/hacbs-test-project-4fbt@sha256:5a5e4f0ff1a4ee2992e50cc92a0169dff7314e5963b9ba8c95c1aa3b01d9e982
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
